import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
    en: {
        siteTitle: "Rate Company Website",
        siteDescription1: "Good experience, their team is professional and seems to know their stuff.",
        siteDescription2: "Our ranking has gone from 20 to 1 in 3 months, they also offer guarantee.",
        searchCompany: "Search Company",
        browseCategory: "Browse Category",
        and: "and",
        privacy: "Privacy",
        terms: "Terms",
        home: "Home",
        contactUs: "Contact Us",
        admin: "Admin",
        login: "Log In",
        logout: "Logout",
        cantFindCompany: "Can't find the company?",
        cantDescription: "Send us a request to add a company to the WeRate database at",
        adminEmail: "hello@werate.co",
        yearFounded: "Year founded",
        headquarter: "Headquarter",
        companySize: "Company size",
        website: "Website",
        email: "Email",
        phone: "Phone",
        claimCompany: "Claim Company",
        edit: "Edit",
        review: "Review",
        reviews: "Reviews",
        smallReviews: "reviews",
        writeReview: "Write Review",
        hotCompany: "Hot Company",
        collCompany: "Cool Company",
        reviewGuidelines: "Review  guidelines",
        guideline1: "Your review should be based on your personal engagement with the company",
        guideline2: "Your service experience with the company must have occurred within the last 12 months",
        guideline3: "You must not name a specific person in your review",
        guideline4: "Review must contain facts and the whole facts only",
        guideline5: "Not offensive or inappropriate words",
        guideline6: "You may not write a review about a Company you have previously or currently own",
        werateRetains: "WeRate retains the right to approve or reject the review you submitted",
        readOurTerms: "Read our terms of use",
        here: "here",
        editCompany: "Edit Company",
        name: "Name",
        description: "Description",
        logo: "Logo",
        banner: "Banner",
        cancel: "Cancel",
        submit: "Submit",
        delete: "Delete",
        dismiss: "Dismiss",
        approve: "Approve",
        reviewSubjectiveOpinion: "This review is the subjective opinion of a WeRate member",
        reviewThisCompany: "Review this Company",
        yourName: "Your name",
        anonymous: "Anonymous",
        keepAnonymous: "Keep this review anonymous",
        reviewTitle: "Review title",
        serviceDetails: "Service details",
        rating: "Rating",
        verify: "Verify",
        optional: "optional",
        wantVerifyReview: "I want to verify my review by submitting supporting document (this will not be published)",
        remove: "Remove",
        yourEmail: "Your email",
        agreeWebrate: "I agree to the WeRate",
        termsOfUse: "Terms of Use",
        certifyReviewSubmit: ". I certify that this review is based on my own experience and is my genuine option of this company, and that I have no personal or business relationship with this establishment, and have not been offered any incentive originating from the company to write this reveiw.",
        reviewSubmitted: "Your review has been submitted!",
        weWillReviewYourSubmission: "We will review your submission and publish it if it complies to our submission rules.",
        ok: "OK",
        welcome: "Welcome",
        loginForAdmin: "Log In for administrator priviledge.",
        password: "Password",
        reviewBy: "Review by",
        administrator: "Administrator",
        adminDescription1: "Admin can create new company under each category, one company can be in more than one category",
        adminDescription2: "Admin can create new company category and category will appear in footer",
        categories: "Categories",
        category: "Category",
        companies: "Companies",
        company: "Company",
        close: "Close",
        selectCategories: "Select Categories",
        messageTitle: "Message title",
        message: "Message",
        thanksForYourMessage: "Thanks for your message!",
        weWillBeInTouch: "We will be in touch with you shortly.",
        hot: "HOT",
        second: "s",
        minute: "m",
        hour: "h",
        day: "d",
        week: "weeks",
        month: "months",
        year: "years",
        ago: "ago",
        whatWasYourServiceReceived: "What was the service you received?",
        reviewContent: "Review",
        services: "Services",
        signIn: 'Sign In',
        signUp: 'Sign Up',
        myProfile: 'My Profile',
        confirmPassword: 'Confirm Password',
        profileHeader: 'Profile',
        firstName: 'First Name',
        lastName: 'Last Name',
        upload: 'Upload',
        changeAvatar: 'Change Avatar',
        statistics: 'Statistics',
        level: 'Level',
        reviewCount: 'Total Review',
        voteCount: 'Good Votes',
    },
    ch: {
        siteTitle: "一齊Upgrade香港",
        siteDescription1: "WeRate是一個服務及公司評分的平台，通過集體讚揚和批評好的和壞的顧客體驗，",
        siteDescription2: "WeRate相信我們可以一齊upgrade香港。",
        searchCompany: "搜索公司",
        browseCategory: "瀏覽公司類別",
        and: "和",
        privacy: "私隱政策",
        terms: "使用條款",
        home: "主頁",
        contactUs: "聯絡我們",
        admin: "管理员",
        login: "登錄",
        logout: "登出",
        cantFindCompany: "找不到要找的公司?",
        cantDescription: "發送電郵給我們添加公司到WeRate的公司數據庫",
        adminEmail: "hello@werate.co",
        yearFounded: "成立年份",
        headquarter: "總部",
        companySize: "公司規模",
        website: "網站",
        email: "電郵",
        phone: "電話",
        claimCompany: "認領公司",
        edit: "编辑",
        review: "評論",
        reviews: "所有評論",
        smallReviews: "評論",
        writeReview: "寫評論",
        hotCompany: "热门公司",
        collCompany: "酷公司",
        reviewGuidelines: "評論指南",
        guideline1: "您的評論應基於您個人與公司接觸的經驗",
        guideline2: "您接受該公司的服務經驗必須發生在過去12個月內",
        guideline3: "您不應在評論中提及你或任何人的名稱或私人資料",
        guideline4: "評論必須包含事實和整個事實",
        guideline5: "評論不應包含冒犯或不怡當的字眼",
        guideline6: "您不得撰寫有關您之前或目前擁有的公司的評論",
        werateRetains: "WeRate保留批准或拒絕您提交的評論的權利",
        readOurTerms: "您可以按閱讀WeRate的使用條款",
        here: "這裡",
        editCompany: "编辑公司",
        name: "名称",
        description: "描述",
        logo: "商标",
        banner: "旗帜",
        cancel: "取消",
        submit: "提交",
        delete: "删除",
        dismiss: "解雇",
        approve: "批准",
        reviewSubjectiveOpinion: "此評論是WeRate用家的主觀意見",
        reviewThisCompany: "寫新評論",
        yourName: "你的名字",
        anonymous: "匿名",
        keepAnonymous: "保持這個評論匿名",
        reviewTitle: "評論標題",
        serviceDetails: "相關服務",
        rating: "評分",
        verify: "評論認證",
        optional: "非必要",
        wantVerifyReview: "我想通過提交文件進行評論驗證 (文件不會被公開）",
        remove: "去掉",
        yourEmail: "你的電郵",
        agreeWebrate: "我同意WeRate",
        termsOfUse: "使用条款",
        certifyReviewSubmit: "。 我保證這個評論是基於我自己的經驗，並且是我對該公司的真正選擇，並且我與該公司沒有任何個人或業務關係，並且沒有從公司獲得任何激勵來撰寫此評論。",
        reviewSubmitted: "您的評論已提交！",
        weWillReviewYourSubmission: "如果符合們的評論指南，您的評論將被發布",
        ok: "確定",
        welcome: "欢迎",
        loginForAdmin: "登录管理员权限。",
        password: "密码",
        reviewBy: "評論者",
        administrator: "管理员",
        adminDescription1: "管理员可以在每个类别下创建新公司，一个公司可以在多个类别中",
        adminDescription2: "管理员可以创建新的公司类别，类别将显示在页脚中",
        categories: "类别",
        category: "类别",
        companies: "公司",
        company: "公司",
        close: "关",
        selectCategories: "选择类别",
        messageTitle: "信息標題",
        message: "信息內容",
        thanksForYourMessage: "謝謝您聯絡們",
        weWillBeInTouch: "我們己收到您的消息，並會盡快回复您",
        hot: "贊助",
        second: "秒",
        minute: "分鐘",
        hour: "小時",
        day: "天",
        week: "星期",
        month: "月",
        year: "年",
        ago: "前",
        whatWasYourServiceReceived: "簡短地ᥥ述你接受的服務內容",
        reviewContent: "評論內容",
        services: "服務",
        signIn: '登入',
        signUp: '註冊',
        myProfile: '簡歷',
        confirmPassword: '確認密碼',
        profileHeader: '輪廓',
        firstName: '名字',
        lastName: '姓',
        upload: '上傳',
        changeAvatar: '改變頭像',
        statistics: '統計',
        level: '水平',
        reviewCount: '總回顧',
        voteCount: '好票',
    }
});

strings.setLanguage('ch');